# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name                      = %q{datapathy}
  s.version                   = "0.6.0"

  s.authors                   = ["Paul Sadauskas"]
  s.date                      = %q{2010-09-01}
  s.email                     = %q{psadauskas@gmail.com}
  s.homepage                  = %q{http://github.com/paul/datapathy}
  s.summary                   = %q{The stupid-simple ORM for HTTP web services}

  s.require_paths             = ["lib"]

  s.files                     = `git ls-files`.split("\n")
  s.test_files                = `git ls-files -- {test,spec,features}/*`.split("\n")

  s.add_runtime_dependency     "activesupport", "> 3.1.0"
  s.add_runtime_dependency     "activemodel",   "> 3.1.0"
  s.add_runtime_dependency     "resourceful"
  s.add_runtime_dependency     "yajl-ruby"

  s.add_development_dependency "uuidtools"
  s.add_development_dependency "rspec"
  s.add_development_dependency "artifice"
  s.add_development_dependency "sinatra"
end

