# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{datapathy}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Sadauskas"]
  s.date = %q{2010-09-01}
  s.email = %q{psadauskas@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.mkd"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.mkd",
     "Rakefile",
     "VERSION",
     "benchmarks/attributes.rb",
     "benchmarks/initialize.rb",
     "benchmarks/query.rb",
     "datapathy.gemspec",
     "lib/datapathy.rb",
     "lib/datapathy/adapters/abstract_adapter.rb",
     "lib/datapathy/adapters/memory_adapter.rb",
     "lib/datapathy/collection.rb",
     "lib/datapathy/model.rb",
     "lib/datapathy/model/crud.rb",
     "lib/datapathy/model/dynamic_finders.rb",
     "lib/datapathy/query.rb",
     "profile/initialize.calltree",
     "profile/initialize.rb",
     "spec/adapter_api_spec.rb",
     "spec/create_spec.rb",
     "spec/crud_spec.rb",
     "spec/datapathy_spec.rb",
     "spec/delete_spec.rb",
     "spec/find_by_spec.rb",
     "spec/find_or_create_spec.rb",
     "spec/query_spec.rb",
     "spec/read_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/support/matchers.rb",
     "spec/support/models.rb",
     "spec/update_spec.rb",
     "spec/validations_spec.rb"
  ]
  s.homepage = %q{http://github.com/paul/datapathy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{The stupid-simple ORM}
  s.test_files = [
    "spec/adapter_api_spec.rb",
     "spec/create_spec.rb",
     "spec/crud_spec.rb",
     "spec/datapathy_spec.rb",
     "spec/delete_spec.rb",
     "spec/find_by_spec.rb",
     "spec/find_or_create_spec.rb",
     "spec/query_spec.rb",
     "spec/read_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/matchers.rb",
     "spec/support/models.rb",
     "spec/update_spec.rb",
     "spec/validations_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<activemodel>, ["~> 3.0.0"])
      s.add_development_dependency(%q<uuidtools>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<activemodel>, ["~> 3.0.0"])
      s.add_dependency(%q<uuidtools>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<activemodel>, ["~> 3.0.0"])
    s.add_dependency(%q<uuidtools>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

